version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      # ignore major versions for keycloak
      - dependency-name: org.keycloak:*
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
