version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: "/keycloak/src/main/docker"
    schedule:
      interval: "daily"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "daily"
