name: Build

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - run: echo "timestamp=`date +"%Y%m%d-%H%M%S"`" >> $GITHUB_ENV
      - run: echo "version=`mvn help:evaluate -Dexpression=version.org.keycloak -DforceStdout -q`" >> $GITHUB_ENV
      - run: echo "major=`mvn help:evaluate -Dexpression=version.org.keycloak -DforceStdout -q | cut -d. -f1`" >> $GITHUB_ENV
      - run: mvn -B -ntp prepare-package -Dcheck.skip -Dimage.tag=${{ env.version }}-${{ env.timestamp }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: docker/login-action docker.io
        uses: docker/login-action@v3.2.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_TOKEN }}
      - name: docker/login-action ghcr.io
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - name: docker/metadata-action temurin
        uses: docker/metadata-action@v5
        id: temurin
        with:
          images: |
            ghcr.io/kokuwaio/keycloak
            docker.io/kokuwaio/keycloak
          tags: |
            latest
            ${{ env.timestamp }}
            ${{ env.version }}
            ${{ env.version }}-${{ env.timestamp }}
            ${{ env.major }}
            ${{ env.major }}-${{ env.timestamp }}
            temurin
            ${{ env.timestamp }}-temurin
            ${{ env.version }}-temurin
            ${{ env.version }}-${{ env.timestamp }}-temurin
            ${{ env.major }}-temurin
            ${{ env.major }}-${{ env.timestamp }}-temurin
      - name: docker/metadata-action temurin-import
        uses: docker/metadata-action@v5
        id: temurin-import
        with:
          images: |
            ghcr.io/kokuwaio/keycloak
            docker.io/kokuwaio/keycloak
          tags: |
            import
            ${{ env.timestamp }}-import
            ${{ env.version }}-import
            ${{ env.version }}-${{ env.timestamp }}-import
            ${{ env.major }}-import
            ${{ env.major }}-${{ env.timestamp }}-import
            temurin-import
            ${{ env.timestamp }}-temurin-import
            ${{ env.version }}-temurin-import
            ${{ env.version }}-${{ env.timestamp }}-temurin-import
            ${{ env.major }}-temurin-import
            ${{ env.major }}-${{ env.timestamp }}-temurin-import
      - name: docker/metadata-action distroless
        uses: docker/metadata-action@v5
        id: distroless
        with:
          images: |
            ghcr.io/kokuwaio/keycloak
            docker.io/kokuwaio/keycloak
          tags: |
            distroless
            ${{ env.timestamp }}-distroless
            ${{ env.version }}-distroless
            ${{ env.version }}-${{ env.timestamp }}-distroless
            ${{ env.major }}-distroless
            ${{ env.major }}-${{ env.timestamp }}-distroless
      - name: docker/metadata-action distroless-import
        uses: docker/metadata-action@v5
        id: distroless-import
        with:
          images: |
            ghcr.io/kokuwaio/keycloak
            docker.io/kokuwaio/keycloak
          tags: |
            distroless-import
            ${{ env.timestamp }}-distroless-import
            ${{ env.version }}-distroless-import
            ${{ env.version }}-${{ env.timestamp }}-distroless-import
            ${{ env.major }}-distroless-import
            ${{ env.major }}-${{ env.timestamp }}-distroless-import
      - name: docker/build-push-action temurin
        uses: docker/build-push-action@v5
        with:
          context: target/docker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.temurin.outputs.tags }}
          target: temurin
      - name: docker/build-push-action temurin-import
        uses: docker/build-push-action@v5
        with:
          context: target/docker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.temurin-import.outputs.tags }}
          target: temurin-import
      - name: docker/build-push-action distroless
        uses: docker/build-push-action@v5
        with:
          context: target/docker
          push: true
          platforms: linux/amd64
          tags: ${{ steps.distroless.outputs.tags }}
          target: distroless
      - name: docker/build-push-action distroless-import
        uses: docker/build-push-action@v5
        with:
          context: target/docker
          push: true
          platforms: linux/amd64
          tags: ${{ steps.distroless-import.outputs.tags }}
          target: distroless-import
