name: Build

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - run: echo "timestamp=`date +"%Y%m%d-%H%M%S"`" >> $GITHUB_ENV
      - run: echo "version=`mvn help:evaluate -Dexpression=version.org.keycloak -DforceStdout -q`" >> $GITHUB_ENV
      - run: echo "major=`mvn help:evaluate -Dexpression=version.org.keycloak -DforceStdout -q | cut -d. -f1`" >> $GITHUB_ENV
      - run: mvn -B prepare-package -Dimage.tag=${{ env.version }}-${{ env.timestamp }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_TOKEN }}
      - uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ghcr.io/kokuwaio/keycloak
            docker.io/kokuwaio/keycloak
          tags: |
            latest
            ${{ env.timestamp }}
            ${{ env.version }}
            ${{ env.version }}-${{ env.timestamp }}
            ${{ env.major }}
            ${{ env.major }}-${{ env.timestamp }}
      - uses: docker/build-push-action@v3
        with:
          context: target/docker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
