name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: avto-dev/markdown-lint@v1
        with:
          args: /github/workspace

  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: limitusus/json-syntax-check@v2.0.0
        with:
          pattern: \\.json$

  dockerfile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context: [base, temurin, temurin-import, distroless, distroless-import]
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/main/docker/${{ matrix.context }}/Dockerfile

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - run: mvn -B -ntp dependency:go-offline
      - run: mvn -B -ntp checkstyle:check

  verify:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    strategy:
      fail-fast: false
      matrix:
        image: [temurin, distroless]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - run: mvn -B -ntp dependency:go-offline
      - run: mvn -B -ntp verify -Dimage.tag.test=${{ matrix.image }} -Dcheckstyle.skip
